canal_tp_postit_homepage:
    pattern:  /
    defaults: { _controller: CanalTPScrumBoardItBundle:Default:index }

canal_tp_postit_add_flag:
    pattern:  /flag/add
    defaults: { _controller: CanalTPScrumBoardItBundle:Default:addFlag }

canal_tp_postit_print:
    pattern:  /print
    defaults: { _controller: CanalTPScrumBoardItBundle:Default:print }

canal_tp_postit_print_patron:
    pattern:  /print/base
    defaults: { _controller: CanalTPScrumBoardItBundle:Print:base }
login:
    pattern:  /login
    defaults: { _controller: CanalTPScrumBoardItBundle:Security:login }
login_check:
    pattern:  /login_check
logout:
    pattern: /logout