# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - main_authenticator
                    - visitor_authenticator
                    - jira_authenticator
                    - github_authenticator
                entry_point: main_authenticator
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
            
    providers:
        webservice:
            id: user_provider
    
    encoders:
        ScrumBoardItBundle\Entity\User: bcrypt