services:
    jira.rest:
        class: CanalTP\ScrumBoardItBundle\Jira\User\JiraRest
        arguments:
            - '%jira_url%'
    ira_auth.user_provider:
        class: CanalTP\ScrumBoardItBundle\Jira\User\JiraUserProvider
        arguments: ['@jira.rest']
        
    service.manager:
        class: CanalTP\ScrumBoardItBundle\Service\ServiceManager
        arguments: ['@service_container']
        calls:
            - [setServiceName, [%issues_service%]]
    jira.service:
        class: CanalTP\ScrumBoardItBundle\Service\JiraService
        arguments: ['@service_container']
        calls:
            - [setOptions, [%jira%]]

    #jira_auth.authentication_success_handler:
    #    class: CanalTP\ScrumBoardItBundle\Security\Authentification\Handler\JiraAuthenticationHandler

    #jira_auth.authentication_failure_handler:
    #    class: CanalTP\ScrumBoardItBundle\Security\Authentification\Handler\JiraAuthenticationHandler

    #jira_auth.authentication_provider:
    #   class: CanalTP\ScrumBoardItBundle\Security\Authentification\Provider\JiraAuthProvider
    #    arguments: ['@jira_auth.user_provider', '', '@jira.rest']
