services:
   user_provider:
       class: ScrumBoardItBundle\Security\User\UserProvider
       arguments:
           - '@doctrine.orm.entity_manager'
   main_authenticator:
       class: ScrumBoardItBundle\Security\MainAuthenticator
       arguments:
           - '@router'
           - '@security.encoder_factory'
   visitor_authenticator:
       class: ScrumBoardItBundle\Security\VisitorAuthenticator
       arguments:
           - '@router'
   jira_authenticator:
       class: ScrumBoardItBundle\Security\JiraAuthenticator
       arguments:
           - '@router'
           - '@api.caller'
           - '@security.token_storage'
   github_authenticator:
       class: ScrumBoardItBundle\Security\GitHubAuthenticator
       arguments:
           - '@router'
           - '@api.caller'
           - '@security.token_storage'
           - 
              host: https://api.github.com/
   discover.api:
       class: ScrumBoardItBundle\Services\Api\ApiVisitor
       arguments:
           - '@request_stack'
   api.caller:
       class: ScrumBoardItBundle\Services\ApiCaller
   jira.api:
       class: ScrumBoardItBundle\Services\Api\ApiJira
       arguments:
           - '@security.token_storage'
           - 
              host: "%jira_url%"
              complexity_field: "%jira_complexity_field%"
              printed_tag: "%jira_printed_tag%"
           - '@api.caller'
   github.api:
       class: ScrumBoardItBundle\Services\Api\ApiGithub
       arguments:
           - '@security.token_storage'
           - 
              host: https://api.github.com/
           - '@api.caller'