services:
   webservice_user_provider:
       class: ScrumBoardItBundle\Security\User\WebServiceUserProvider
       arguments:
           - '@doctrine.orm.entity_manager'
   api.caller:
       class: ScrumBoardItBundle\Services\ApiCaller
  # jira_token_authenticator:
  #    class: ScrumBoardItBundle\Security\JiraAuthenticator
  #     arguments:
  #         - '@router'
  #         - 
  #            host: "%jira_url%"
  #            complexity_field: "%jira_complexity_field%"
  #            printed_tag: "%jira_printed_tag%"
  #         - '@api.caller'
  # github_token_authenticator:
  #     class: ScrumBoardItBundle\Security\GitHubAuthenticator
  #     arguments:
  #         - '@router'
  #         - 
  #            host: https://api.github.com/
  #         - '@api.caller'
   sbi_authenticator:
       class: ScrumBoardItBundle\Security\SbiAuthenticator
       arguments:
           - '@router'
   visitor_authenticator:
       class: ScrumBoardItBundle\Security\VisitorAuthenticator
       arguments:
           - '@router'
           - 
              host: https://api.github.com/
           - '@api.caller'
   jira.api:
       class: ScrumBoardItBundle\Services\Api\ApiJira
       arguments:
           - '@security.token_storage'
           - 
              host: "%jira_url%"
              complexity_field: "%jira_complexity_field%"
              printed_tag: "%jira_printed_tag%"
           - '@api.caller'
   github.api:
       class: ScrumBoardItBundle\Services\Api\ApiGithub
       arguments:
           - '@security.token_storage'
           - 
              host: https://api.github.com/
           - '@api.caller'
   discover.api:
       class: ScrumBoardItBundle\Services\Api\ApiVisitor
       arguments:
           - '@request_stack'
           - '@security.token_storage'
           - 
              host: https://api.github.com/
           - '@api.caller'